ASPNETWebApp/Models/CalculatorModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ASPNETWebApp.Models
{
    public class CalculatorModel
    {
        [Required]
        [Range(0, 100, ErrorMessage = "Invalid assignments entry. Please enter a grade between 0 and 100.")] //(learned this from the microsoft website, should work) By limiting the range input,
                                                                                                 //the model will throw the user an error if the entry is invalid before posting the data.
        public int Assignments { get; set; }
        [Required] //First I throw the required to indicate this needs to be filled out 
        [Range(0, 100, ErrorMessage = "Invalid group project entry. Please enter a grade between 0 and 100.")] //then I use a range to get the correct input
        public int GP { get; set; } //finally I get the for input and set the data to the value variable 
        [Required]
        [Range(0, 100, ErrorMessage = "Invalid quizzes entry. Please enter a grade between 0 and 100.")]
        public int Q { get; set; }
        [Required]
        [Range(0, 100, ErrorMessage = "Invalid midterm exam entry. Please enter a grade between 0 and 100.")]
        public int ME { get; set; }
        [Required]
        [Range(0, 100, ErrorMessage = "Invalid final exam entry. Please enter a grade between 0 and 100.")]
        public int FE { get; set; }
        [Required]
        [Range(0, 100, ErrorMessage = "Invalid intex entry. Please enter a grade between 0 and 100.")]
        public int I { get; set; }

    }

}

ASPNETWebApp/Controllers/BlahController.cs
using ASPNETWebApp.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ASPNETWebApp.Controllers //these controller actions are called when the html pages are nagivated
    //to, it will display the view which is essentially the html page
{
    public class BlahController : Controller
    {
        public IActionResult Index () //calling the index home page
        {
            return View();
        }
        
        [HttpGet]
        public IActionResult Calculator () //public classes are used so that they can be called and viewed on the main page
        {
            return View();
        }
        //above calls the calculator form page, below posts the calculator form inputs using the model
        [HttpPost]
        public IActionResult Calculator(CalculatorModel model)
        {
            return View();
        }
    }
}

ASPNETWebApp/Views/Blah/Calculator.cshtml
@*
    //For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
    *@
@{
    ViewData["Title"] = "Kate Opager's Killer Site";
}
@model CalculatorModel 

<h2 style="color:rosybrown; font-weight:bolder"> Calculate your grade</h2>
<br />
<p>
    Input the total percentage you received for each category into the calculator form below. <br />The final grade will be estimated
    and then output based off these submissions.Please only submit a valid number from 0 to 100.
</p>
<br />
<form method="post">
    <!--in the form I created inputs that receive number values, give them ids(to pass to the js function), and at the end submit them with the button-->
    <!--Side note: the asp-for is assigning the input to the same name in the Calculator Model so that the inputs can get get/set and validated.-->
    <label> Assignments </label> <br />
    <input id="Assignments" type="number" asp-for="Assignments"/> <br />
    <label> Group Project </label> <br />
    <input id="GP" type="number" asp-for="GP"/> <br />
    <label> Quizzes</label> <br />
    <input id="Q" type="number" asp-for="Q" /><br />
    <label> Midterm Exam </label> <br />
    <input id="ME" type="number" asp-for="ME" /> <br />
    <label> Final Exam </label> <br />
    <input id="FE" type="number" asp-for="FE"/> <br />
    <label> Intex </label> <br />
    <input id="I" type="number" asp-for="I" /> <br /> <br />
    <input id="calculate" type="submit" style="border:none;background-color:rosybrown;color:floralwhite;font-weight:bolder" value="Submit" /><br /><br />
    
    <div asp-validation-summary ="All">
    </div>

</form>
<div>
    <p id="result" style="font-size:30px"></p>
</div>
<!--The scripts below should be including the js calculator, the jquery shortcut/library, and the bootstrap library-->
<script src="js/GradeCalculator.js"></script>

ASPNETWebApp/Views/Blah/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Kate Opager's Killer Site"; /*I am setting the title razor code variable to what I want displayed on this page. The variable is on the layout page */
}

<!--I created a header, and then a paragraph with information about my hopes with this class, a picture from my wedding day, and some listed jobs-->
<header>
    <h1 style="color:antiquewhite"> Kate Opager </h1>
</header>

<img src="img/6O2A9146.JPEG" />
<h1>
    This photo is from my wedding day, <br /> but I love hanging out with my friends! <br />
</h1>
<br />
<p style="padding-left:25%;padding-right:25%">
    A lot of IS concepts feel easy to understand, but then  when I go to write a program or complete a homework task
    I often feel completely lost. I'm hoping that this class will help with my overall understanding of programs and improve my programmer way of thinking.
    I think that this class will also challenge me and help improve my overall problem solving skills. Sometimes I get frustrated with code and want to quit, but
    this class will encourage me to keep trying and I'm eager to see all the new hard and soft skills that will come because of the struggle of it.
</p>
<br />
<p> </p>

<p style="font-size:25px;font-weight:bold">Kate's ideal jobs post graduation:</p>
<ul>
    <li>Technology Consulting</li>
    <li>Project Management</li>
    <li>Cyber Security</li>
</ul>

ASPNETWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    @*<title>@ViewBag.Title</title>*@
    <meta charset="utf-8" />
    <title>@ViewData["Title"]</title> @*this razor code allows for each page to set a title while using the layout*@
    <link rel="icon" type="image/x-icon" href="img/favicon.ico" />
    <link href="lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="css/kate.css" rel="stylesheet" />
</head>

<body>

    @* nav bar using the tag helpers from view imports to direct to and from these pages*@
    <nav>
        <a asp-controller="Blah" asp-action="Index"> Home</a>
        <a asp-controller="Blah" asp-action="Calculator" > Grade Calculator</a>
    </nav>

    @*the render body will give us the cshtml pages and put them into a formatted body following this layout*@
    <div>
        @RenderBody()
    </div>


    @*the follow scripts are calling our bootstrap and jquery library to each page using the layout*@
    <script src="lib/bootstrap/js/bootstrap.min.js"></script>
    <script src="lib/jquery/jquery-3.6.3.min.js"></script>

</body>

</html>